### PR TITLE
Adds Testing to /getincidents Endpoint

### PR DESCRIPTION
**Pull request by devbrunopaula**
# Description
Adds Testing to Get All Incidents endpoint.

## Type of change
Please delete options that are not relevant.
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Change Status
- [x] Complete, tested, ready to review and merge
- [ ] Complete, but not tested (may need new tests)
- [ ] Incomplete/work-in-progress, PR is for discussion/feedback

# How Has This Been Tested?
- [x] Integration Test - Jest
Screen Shot 2021-08-09 at 6 58 48 PM

# Checklist
- [ ] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] My code has been reviewed by at least one peer
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] There are no merge conflicts

### CODE REVIEW

**Review by RowenWitt — DISMISSED** [review]
Couple typos on tests but they all make sense for sanity checks, switching force_ranks from incidents on the knex migration is good.

**Review by RyderBlues — COMMENTED** [review]
'testt' on line ten should be 'test', 'fecth' on line 16 and 21 should 'fetch'.

**Review by joseph-witzke — CHANGES_REQUESTED** [review]
Overall looks good, but I think we need to confirm we're requiring the correct files -- i.e. dbconfig, and the incidents-model.js.

Also, I think you added the package.lcok.json which may cause some issuses.

**Comment by dylan-rinella** [comment]
One suggestion would be to change the testt (line 10) description to something more descriptive. The other guys nailed the other concerns. Looks good overall!

**Comment by devbrunopaula** [comment]
You Guys are the Best, Thanks for all the comments.

**Comment by devbrunopaula** [comment]
> Overall looks good, but I think we need to confirm we're requiring the correct files -- i.e. dbconfig, and the incidents-model.js.
> 
> Also, I think you added the package.lcok.json which may cause some issuses.

Joe as far as I know  per NPM Documentation package.lock.json is highly recommended and intended to be committed.

###  Doc Link
https://docs.npmjs.com/cli/v7/configuring-npm/package-lock-json

**Review by joseph-witzke — APPROVED** [review]
I think this is good to go...glad you were able to sort out the issues yesterday. Great work!

**Review by RyderBlues — APPROVED** [review]
Good to go!

**Pull request merged**
